package org.dcsa.standards.specifications.standards.cs.v100;

import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.headers.Header;
import io.swagger.v3.oas.models.media.ArraySchema;
import io.swagger.v3.oas.models.media.Content;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.tags.Tag;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;
import org.dcsa.standards.specifications.generator.QueryParametersFilterEndpoint;
import org.dcsa.standards.specifications.generator.SpecificationToolkit;
import org.dcsa.standards.specifications.standards.cs.v1.Cs1StandardSpecification;
import org.dcsa.standards.specifications.standards.cs.v100.messages.DetailedError;
import org.dcsa.standards.specifications.standards.cs.v100.messages.ErrorResponse;
import org.dcsa.standards.specifications.standards.cs.v100.model.*;

/** CS 1.0.0 Point-to-Point Routings standard specification module. */
public class CsP2p100StandardSpecification extends Cs1StandardSpecification {

  public static final String TAG_P2P = "Point To Point";

  private final GetPointToPointRoutesEndpoint getPointToPointRoutesEndpoint;

  public CsP2p100StandardSpecification() {
    this("1.0.0", "");
  }

  protected CsP2p100StandardSpecification(String versionNumber, String baselineVersion) {
    super("Point to Point", "p2p", versionNumber, baselineVersion);

    getPointToPointRoutesEndpoint = new GetPointToPointRoutesEndpoint();

    openAPI.addTagsItem(new Tag().name(TAG_P2P).description(" "));

    openAPI.path("/v1/point-to-point-routes", new PathItem().get(operationPointToPointGet()));

    // The YAML oneOf for Leg.transport has no discriminator; strip the empty one generated by
    // swagger-core
    Schema<?> legSchema = openAPI.getComponents().getSchemas().get(Leg.class.getSimpleName());
    if (legSchema != null && legSchema.getProperties() != null) {
      Schema<?> transportProp = (Schema<?>) legSchema.getProperties().get("transport");
      if (transportProp != null) {
        transportProp.setDiscriminator(null);
      }
    }
  }

  @Override
  protected Stream<Class<?>> modelClassesStream() {
    return Stream.of(
        Address.class,
        Barge.class,
        BargeTransport.class,
        CutOffTime.class,
        DetailedError.class,
        ErrorResponse.class,
        Facility.class,
        Leg.class,
        Location.class,
        OtherTransport.class,
        PlaceOfArrival.class,
        PlaceOfDeparture.class,
        PlaceOfDelivery.class,
        PlaceOfReceipt.class,
        PointToPoint.class,
        ServicePartner.class,
        Vessel.class,
        VesselTransport.class);
  }

  @Override
  protected List<String> getRootTypeNames() {
    return List.of(PointToPoint.class.getSimpleName());
  }

  @Override
  protected QueryParametersFilterEndpoint getQueryParametersFilterEndpoint() {
    return getPointToPointRoutesEndpoint;
  }

  private Operation operationPointToPointGet() {
    return new Operation()
        .summary("Point to Point Routing")
        .description(
"""
Provides the product offering of single or multiple estimated end-to-end route options for a shipment in the pre-booking phase. This includes point-to-point specification of all transport legs, estimated timings, estimated schedules and interdependencies between transport legs.

The list of solutions returned in the response can be tailored to a specific need by combining available query parameters.

The minimum required query parameters are `placeOfReceipt` and `placeOfDelivery`. If no further query parameters are used to tailor the response, the provider of the GET endpoint will return their best suggestions in the response.

The `GET /v1/point-to-point-routes` endpoint can be implemented independently of having implemented the `GET /v1/port-schedules`  and `GET /v1/vessel-schedules`  endpoints.
""")
        .operationId("get-v1-point-to-point")
        .tags(Collections.singletonList(TAG_P2P))
        .parameters(
            Stream.concat(
                    getPointToPointRoutesEndpoint.getQueryParameters().stream(),
                    Stream.of(getApiVersionHeaderParameter()))
                .toList())
        .responses(
            new ApiResponses()
                .addApiResponse(
                    "200",
                    new ApiResponse()
                        .description("OK")
                        .headers(
                            new LinkedHashMap<>(
                                Map.ofEntries(
                                    Map.entry(
                                        API_VERSION_HEADER,
                                        new Header().$ref(API_VERSION_HEADER_REF)))))
                        .content(
                            new Content()
                                .addMediaType(
                                    "application/json",
                                    new MediaType()
                                        .schema(
                                            new ArraySchema()
                                                .items(
                                                    new Schema<>()
                                                        .$ref(
                                                            SpecificationToolkit
                                                                .getComponentSchema$ref(
                                                                    PointToPoint.class)))))))
                .addApiResponse("400", createErrorResponse("Bad Request"))
                .addApiResponse("500", createErrorResponse("Internal Server Error")));
  }

  private ApiResponse createErrorResponse(String description) {
    return new ApiResponse()
        .description(description)
        .headers(
            new LinkedHashMap<>(
                Map.ofEntries(
                    Map.entry(API_VERSION_HEADER, new Header().$ref(API_VERSION_HEADER_REF)))))
        .content(
            new Content()
                .addMediaType(
                    "application/json",
                    new MediaType()
                        .schema(
                            new Schema<>()
                                .$ref(
                                    SpecificationToolkit.getComponentSchema$ref(
                                        ErrorResponse.class)))));
  }
}
