/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 21-Oct-2020 12:24:09 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS dcsa_ebl_v1_0.booking CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.cargo_item CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.cargo_item_equipment CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.carrier CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.carrier_clauses CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.charges CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.contact_details CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.country CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.displayed_address CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.ebl_endorsement_chain CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.equipment CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.iso_equipment_code CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.facility CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.facility_type CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.hs_code CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.location CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.mode_of_transport CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.package_code CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.party CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.party_function CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.party_location CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.reference_type CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.references CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.seal CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.seal_source CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.seal_type CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.service_type CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.shipment CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.shipment_equipment CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.shipment_location CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.shipment_location_type CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.shipment_party CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.shipment_term CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.shipment_transport CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.shipping_instruction CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.transport CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.transport_call CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.transport_call_voyage CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.transport_document CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.transport_document_carrier_clauses CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.transport_document_type CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.transport_document_party CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.un_location CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.vessel CASCADE;
DROP TABLE IF EXISTS dcsa_ebl_v1_0.voyage CASCADE;

/* Create Tables */

CREATE TABLE dcsa_ebl_v1_0.booking (
	carrier_booking_reference varchar(35) PRIMARY KEY,
	shipment_id uuid NULL,
	service_type_at_origin varchar(5) NULL,
	service_type_at_destination varchar(5) NULL,
	shipment_term_at_origin varchar(5) NULL,
	shipment_term_at_destination varchar(5) NULL,
	booking_datetime timestamp with time zone NULL,	-- The date and time of the booking request.
	service_contract varchar(30)
);

CREATE TABLE dcsa_ebl_v1_0.cargo_item (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	shipment_id uuid NOT NULL,
	commodity_type varchar(20) NULL,	-- HS6: e.g. 2468 which could be metal
	shipping_marks text NULL,
	description_of_goods text NULL,
	hs_code varchar(10) NULL,
	weight real NULL,
	volume real NULL,
	weight_unit varchar(20) NULL,
	volume_unit varchar(20) NULL,
	number_of_packages integer NULL,
	carrier_booking_reference varchar(35) NULL,
	shipping_instruction_id uuid NULL
);

CREATE TABLE dcsa_ebl_v1_0.cargo_item_equipment (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	cargo_item_id uuid NOT NULL,
	equipment_id uuid NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.carrier (
    carrier_code varchar(10) PRIMARY KEY,
    code_list_provider_code varchar(4),
    carrier_name varchar(100),
    code_list_provider varchar(8)
);

CREATE TABLE dcsa_ebl_v1_0.carrier_clauses (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	clause_content text NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.charges (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	shipment_id uuid NOT NULL,
	transport_document_id uuid NULL,
	charge_type varchar(20) NULL,
	amount real NULL,
	currency varchar(3) NULL,
	payment_term varchar(3) NULL,
	calculation_basis varchar(50) NULL,
	freight_payable_at uuid NULL,
	display_charges boolean NULL,
	unit_price real NULL,
	quantity real NULL
);

CREATE TABLE dcsa_ebl_v1_0.contact_details (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	phone_number varchar(20) NULL,
	email varchar(250) NULL,
	fax varchar(20) NULL,
	location_id uuid NULL
);

CREATE TABLE dcsa_ebl_v1_0.country (
	country_code varchar(2) PRIMARY KEY,
	country_name varchar(75) NULL
);

CREATE TABLE dcsa_ebl_v1_0.displayed_address (
	transport_document_id uuid NOT NULL,
	party_id uuid NOT NULL,
	displayed_address varchar(250) NULL
);

CREATE TABLE dcsa_ebl_v1_0.ebl_endorsement_chain (
	transport_document_id uuid NOT NULL,
	title_holder uuid NOT NULL,  -- reference to Party
	signature varchar(500) NOT NULL,	-- Digital signature of the previous title holder
	endorsement_date date NOT NULL,
	endorsee uuid NOT NULL  -- reference to Party
);

ALTER TABLE dcsa_ebl_v1_0.ebl_endorsement_chain ADD CONSTRAINT "pk_ebl_endorsement_chain"
    PRIMARY KEY (title_holder,transport_document_id)
;

CREATE TABLE dcsa_ebl_v1_0.equipment (
	equipment_reference varchar(15) PRIMARY KEY,	-- The unique identifier for the equipment, which should follow the BIC ISO Container Identification Number where possible. According to ISO 6346, a container identification code consists of a 4-letter prefix and a 7-digit number (composed of a 3-letter owner code, a category identifier, a serial number and a check-digit). If a container does not comply with ISO 6346, it is suggested to follow Recommendation #2 “Container with non-ISO identification” from SMDG.
	iso_equipment char(4) NULL,	-- Unique code for the different equipment size/type used for transporting commodities. The code is a concatenation of ISO Equipment Size Code and ISO Equipment Type Code A and follows the ISO 6346 standard.
	tare_weight real NULL,
	weight_unit varchar(20) NULL
);

CREATE TABLE dcsa_ebl_v1_0.iso_equipment_code (
    iso_equipment_code text PRIMARY KEY,
    iso_equipment_name text NULL,
    iso_equipment_size_code text NULL,
    iso_equipment_type_code_a text NULL
);

CREATE TABLE dcsa_ebl_v1_0.facility (
    facility_code varchar(11) PRIMARY KEY,
    facility_name varchar(100) NULL,
    code_list_provider_code varchar(6) NULL,
    code_list_provider varchar(8) NULL,
    un_location_code varchar(5) NULL,
    latitude varchar(10) NULL,
    longitude varchar(11) NULL,
    address varchar(250) NULL,
    facility_type varchar(4) NULL
);

CREATE TABLE dcsa_ebl_v1_0.facility_type (
    facility_type_code varchar(4) PRIMARY KEY,
    facility_type_name varchar(100) NULL,
    facility_type_description varchar(250) NULL
);

CREATE TABLE dcsa_ebl_v1_0.hs_code (
	hs_code varchar(10) PRIMARY KEY,
	code_description varchar(250) NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.location (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	address varchar(250) NULL,
	latitude varchar(10) NULL,
	longitude varchar(11) NULL,
	un_location_code char(5) NULL
);

CREATE TABLE dcsa_ebl_v1_0.mode_of_transport (
	mode_of_transport_code varchar(3) PRIMARY KEY,	-- The code specifying the mode (e.g. transport by rail) for the transport. The code follows UN/CEFACT Recommendation 19 - Codes for Modes of Transport.
	mode_of_transport_name varchar(100) NULL,	-- The name of the mode of transport. The code follows UN/CEFACT Recommendation 19 - Codes for Modes of Transport
	mode_of_transport_description varchar(250) NULL,	-- The description of the mode of transport as detailed by UN/CEFACT Recommendation 19 - Codes for Modes of Transport
	dcsa_transport_type varchar(50) NULL	-- The DCSA defined types of transport as used in events linked to the Mode of Transport.
);

CREATE TABLE dcsa_ebl_v1_0.package_code (
	package_code varchar(10) PRIMARY KEY,	-- e.g. UN00001899
	description varchar(50) NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.party (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	party_name varchar(100) NULL,
	tax_reference varchar(20) NULL,
	public_key varchar(500) NULL
);

CREATE TABLE dcsa_ebl_v1_0.party_function (
    party_function_code varhcar(3) PRIMARY KEY,
    party_function_name varchar(100),
    party_function_description varchar(250)
);

CREATE TABLE dcsa_ebl_v1_0.party_location (
	location_id uuid NOT NULL,
	party_id uuid NOT NULL
);

ALTER TABLE dcsa_ebl_v1_0.party_location ADD CONSTRAINT "pk_party_location"
    PRIMARY KEY (location_id,party_id)
;

CREATE TABLE dcsa_ebl_v1_0.reference_type (
	reference_type_code varchar(3) PRIMARY KEY,
	reference_name varchar(20) NOT NULL,
	reference_description varchar(200) NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.references (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	reference_type varchar(3) NOT NULL,	-- e.g. CR, PO, SI, FF
	reference_value varchar(50) NOT NULL,
	shipment_id uuid NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.seal (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	shipment_equipment_id uuid NOT NULL,
	seal_number varchar(15) NOT NULL,
	seal_source varchar(5) NULL,
	seal_type varchar(4) NULL
);

CREATE TABLE dcsa_ebl_v1_0.seal_source (
	seal_source_code varchar(5) PRIMARY KEY,
	description varchar(50) NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.seal_type (
	seal_type_code varchar(4) NOT PRIMARY KEY,
	description varchar(50) NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.service_type (
	service_type varchar(5) PRIMARY KEY,
	description varchar(200) NULL
);

CREATE TABLE dcsa_ebl_v1_0.shipment (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
-- 	transport_document_id uuid NULL,	-- Bill of lading number is an identifier that links to a shipment. Bill of lading is the legal document issued to the customer which confirms the carrier's receipt of the cargo from the customer acknowledging goods being shipped and specifying the terms of delivery.
	collection_datetime timestamp with time zone NULL,	-- The date and the time that the shipment items need to be collected from the origin.
	delivery_datetime timestamp with time zone NULL,	-- The date (and when possible time) that the shipment items need to be delivered to the destination.
	carrier_code varchar(10) NULL,	-- The Carrier Code represents a concatenation of the Code List Provider Code and the Code List Provider. A hyphen is used between the two codes. The unique carrier identifier is sourced from either the NMFTA SCAC codes list or the SMDG Master Liner codes list.
	confirmed_equipment_type varchar(4) NULL,
	confirmed_equipment_units integer NULL
);

CREATE TABLE dcsa_ebl_v1_0.shipment_equipment (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	shipment_id uuid NULL,
	equipment_reference varchar(15) NULL,
	total_container_weight real NULL,
	verified_gross_mass real NULL,
	weight_unit varchar(20) NULL
);

CREATE TABLE dcsa_ebl_v1_0.shipment_location (
	shipment_id uuid NOT NULL,
	location_id uuid NOT NULL,
	location_type varchar(3) NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.shipment_location_type (
	location_type_code varchar(3) PRIMARY KEY,
	location_type_description varchar(50) NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.shipment_party (
	party_id uuid NOT NULL,
	shipment_id uuid NOT NULL,
	party_role varchar(20) NOT NULL,
	notification_flag boolean NULL
);

CREATE TABLE dcsa_ebl_v1_0.shipment_term (
	shipment_term varchar(5) PRIMARY KEY,
	description varchar(200) NULL
);

CREATE TABLE dcsa_ebl_v1_0.shipment_transport (
	shipment_id uuid NOT NULL,
	transport_id uuid NOT NULL,
	sequence_number integer NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.shipping_instruction (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	shipment_id uuid NOT NULL,
	callback_url text NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.transport (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	transport_reference varchar(50) NULL,	-- The reference for the transport, e.g. when the mode of transport is a vessel, the Transport Reference will be the vessel IMO number.
	transport_name varchar(100) NULL,	-- The name of the particular transport instance, e.g. for a vessel this is the vessel name
	mode_of_transport varchar(3) NOT NULL,	-- The code specifying the means of transport, e.g. the named vessel executing the transporting.
	load_transport_call_id uuid NOT NULL,
	discharge_transport_call_id uuid NOT NULL,
	vessel uuid NULL
);

CREATE TABLE dcsa_ebl_v1_0.transport_call (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	transport_call_sequence_number varchar(50) NULL,	-- Transport operator's key that uniquely identifies each individual call. Essential to distinguish between 2 separate calls at the same location.
	facility_code varchar(11) NULL,
	facility_type char(4) NULL,
	other_facility varchar(50) NULL,
	customer_address varchar(250) NULL,
	location_id uuid NULL
);

CREATE TABLE dcsa_ebl_v1_0.transport_call_voyage (
	transport_call_id uuid NOT NULL,
	voyage_id uuid NOT NULL
);

CREATE TABLE dcsa_ebl_v1_0.transport_document (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	transport_document_type varchar(3) NULL,
	place_of_issue uuid NULL,
	onboard_date date NULL,
	received_for_shipment_date date NULL,
	document_reference_number varchar(20) NULL,
	number_of_originals integer NULL,
	terms_and_conditions text NULL,
	issuer uuid NULL,	-- name of the carrier who issues the BL
	document_status varchar(50) NULL,	-- SI, Received, Drafted, Pending Approval, Approved, Issued, Surrendered
	shipping_instruction UUID NULL,
	declared_value real NULL,
	declared_value_currency varchar(3) NULL
);

CREATE TABLE dcsa_ebl_v1_0.transport_document_carrier_clauses (
	carrier_clauses_id uuid NOT NULL,
	transport_document_id uuid NOT NULL
);

ALTER TABLE dcsa_ebl_v1_0.transport_document_carrier_clauses ADD CONSTRAINT "pk_transport_document_carrier_clauses"
    PRIMARY KEY (carrier_clauses_id,transport_document_id)
;

CREATE TABLE dcsa_ebl_v1_0.transport_document_party (
	party_id uuid NOT NULL,
	transport_document_id uuid NOT NULL,
	displayed_address varchar(250) null,
	party_contact_details varchar(250) null
);

ALTER TABLE dcsa_ebl_v1_0.transport_document_carrier_clauses ADD CONSTRAINT "pk_transport_document_carrier_clauses"
    PRIMARY KEY (carrier_clauses_id,transport_document_id)
;

CREATE TABLE dcsa_ebl_v1_0.transport_document_type (
	transport_document_type_code varchar(3) PRIMARY KEY,	-- The type of the transport document (i.e. BOL (bill of lading) or SWB (Sea Waybill).  @adding eBL
	transport_document_type_name varchar(20) NULL,	-- The full names of the document types (Bill of Lading or Sea Waybill).
	transport_document_type_description varchar(200) NULL	-- A description of the different document types.
);

CREATE TABLE dcsa_ebl_v1_0.un_location (
	un_location_code char(5) PRIMARY KEY,	-- The UN Location Code identifies a location in the sense of a city/a town/a village, being the smaller administrative area existing as defined by the competent national authority in each country. A complete UN Location Code is a combination of a 2-character country code and a 3-character city/town/area LOCODE, e.g. BEANR is known as the city of Antwerp (ANR), which is located in Belgium (BE).
	un_location_name varchar(100) NULL,	-- The name of the location as defined by the UN/ECE
	location_code char(3) NULL,	-- Location Code identifies a location in the sense of a city/a town/a village, being the smaller administrative area existing as defined by the competent national authority in each country. Location Code is a 3-character code e.g. ANR for Antwerp.
	country_code char(2) NULL	-- The two-letter ISO 3166 country code. E.g. BE for Belgium.
);

CREATE TABLE dcsa_ebl_v1_0.vessel (
	vessel_imo_number varchar(7) PRIMARY KEY,	-- The unique reference for a registered Vessel. The reference is the International Maritime Organization (IMO) number, also sometimes known as the Lloyd's register code.
	vessel_name varchar(35) NULL,	-- The name of the Vessel given by the Vessel Operator e.g. Emma Maersk
	vessel_flag char(2) NULL,	-- The flag of the vessel e.g. DK
	vessel_call_sign_number varchar(10) NULL,	-- A unique alphanumeric identity that belongs to the vessel.  Each Call Sign begins with the Call Sign alphanumeric prefix that indicates nationality, e.g. prefixes allocated to the United Kingdom are 2, G, M, VP-VQ, VS, ZB-ZJ, ZN-ZO and ZQ. The prefix is usually followed by 2 or 3 alphanumeric characters.  For example, Cunard Lines Queen Mary 2 has the Call Sign W6RO.
	vessel_operator_carrier_code varchar(10) NULL	-- The carrier who is in charge of the vessel operations
);

CREATE TABLE dcsa_ebl_v1_0.voyage (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,	-- The identifier of the Voyage.
	carrier_voyage_number varchar(50) NULL,	-- The identifier of the Voyage. The identifier is vessel operator specific.
	service_id uuid NULL	-- The identifier of the Service.
);

/* Create Foreign Key Constraints */

ALTER TABLE dcsa_ebl_v1_0.booking ADD CONSTRAINT "FK_Booking_Shipment"
	FOREIGN KEY (shipment_id) REFERENCES dcsa_ebl_v1_0.shipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.cargo_item ADD CONSTRAINT "FK_Cargo Item_HS Code"
	FOREIGN KEY (hs_code) REFERENCES dcsa_ebl_v1_0.hs_code (hs_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.cargo_item ADD CONSTRAINT "FK_Cargo Item_Shipping Instruction"
	FOREIGN KEY (shipping_instruction_number) REFERENCES dcsa_ebl_v1_0.shipping_instruction (shipping_instruction_number) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.cargo_item ADD CONSTRAINT "FK_Commodity_Shipment"
	FOREIGN KEY (shipment_id) REFERENCES dcsa_ebl_v1_0.shipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.cargo_item_equipment ADD CONSTRAINT "FK_Shipment Equipment Commodity_Shipment Equipment"
	FOREIGN KEY (shipment_equipment_id) REFERENCES dcsa_ebl_v1_0.shipment_equipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.cargo_item_equipment ADD CONSTRAINT "FK_Shipment Equipment_Commodity"
	FOREIGN KEY (cargo_item_id) REFERENCES dcsa_ebl_v1_0.cargo_item (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.charges ADD CONSTRAINT "FK_Charges_Location"
	FOREIGN KEY (freight_payable_at) REFERENCES dcsa_ebl_v1_0.location (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.charges ADD CONSTRAINT "FK_Charges_Shipment"
	FOREIGN KEY (shipment_id) REFERENCES dcsa_ebl_v1_0.shipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.contact_details ADD CONSTRAINT "FK_Contact Details_Location"
	FOREIGN KEY (location_id) REFERENCES dcsa_ebl_v1_0.location (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.displayed_address ADD CONSTRAINT "FK_Printed Address_Party"
	FOREIGN KEY (party_id) REFERENCES dcsa_ebl_v1_0.party (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.displayed_address ADD CONSTRAINT "FK_Printed Address_Transport Document"
	FOREIGN KEY (transport_document_id) REFERENCES dcsa_ebl_v1_0.transport_document (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.ebl_endorsement_chain ADD CONSTRAINT "FK_EBL Change Signing Parties_Party"
	FOREIGN KEY (title_holder) REFERENCES dcsa_ebl_v1_0.party (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.ebl_endorsement_chain ADD CONSTRAINT "FK_EBL Endorsement Chain_Party"
	FOREIGN KEY (endorsee) REFERENCES dcsa_ebl_v1_0.party (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.ebl_endorsement_chain ADD CONSTRAINT "FK_EBL Endorsement Chain_Transport Document"
	FOREIGN KEY (transport_document_id) REFERENCES dcsa_ebl_v1_0.transport_document (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.location ADD CONSTRAINT "FK_Location_UN Location"
	FOREIGN KEY (un_location_code) REFERENCES dcsa_ebl_v1_0.un_location (un_location_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.package_code ADD CONSTRAINT "FK_Standard Package Code_Shipment Item"
	FOREIGN KEY (cargo_item_id) REFERENCES dcsa_ebl_v1_0.cargo_item (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.party ADD CONSTRAINT "FK_Party_Location"
	FOREIGN KEY (contact_details_id) REFERENCES dcsa_ebl_v1_0.contact_details (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.party_location ADD CONSTRAINT "FK_Party Location_Location"
	FOREIGN KEY (location_id) REFERENCES dcsa_ebl_v1_0.location (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.party_location ADD CONSTRAINT "FK_Party Location_Party"
	FOREIGN KEY (party_id) REFERENCES dcsa_ebl_v1_0.party (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.references ADD CONSTRAINT "FK_References_Reference Type"
	FOREIGN KEY (reference_type) REFERENCES dcsa_ebl_v1_0.reference_type (reference_type_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.references ADD CONSTRAINT "FK_References_Shipment"
	FOREIGN KEY (shipment_id) REFERENCES dcsa_ebl_v1_0.shipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.seal ADD CONSTRAINT "FK_Seal_Seal Source"
	FOREIGN KEY (seal_source_id) REFERENCES dcsa_ebl_v1_0.seal_source (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.seal ADD CONSTRAINT "FK_Seal_Seal Type"
	FOREIGN KEY (seal_type_id) REFERENCES dcsa_ebl_v1_0.seal_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.seal ADD CONSTRAINT "FK_Seal_Shipment Equipment"
	FOREIGN KEY (shipment_equipment_id) REFERENCES dcsa_ebl_v1_0.shipment_equipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment ADD CONSTRAINT "FK_Shipment_Mode Of Transport"
	FOREIGN KEY (pre_carrier_mode_of_transport) REFERENCES dcsa_ebl_v1_0.mode_of_transport (mode_of_transport_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_equipment ADD CONSTRAINT "FK_Shipment Equipment_Equipment"
	FOREIGN KEY (equipment_reference) REFERENCES dcsa_ebl_v1_0.equipment (equipment_reference) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_equipment ADD CONSTRAINT "FK_Shipment Equipment_Shipment"
	FOREIGN KEY (shipment_id) REFERENCES dcsa_ebl_v1_0.shipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_location ADD CONSTRAINT "FK_Shipment Location_Location"
	FOREIGN KEY (location_id) REFERENCES dcsa_ebl_v1_0.location (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_location ADD CONSTRAINT "FK_Shipment Location_Location Type"
	FOREIGN KEY (location_type) REFERENCES dcsa_ebl_v1_0.shipment_location_type (location_type_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_location ADD CONSTRAINT "FK_Shipment Location_Shipment"
	FOREIGN KEY (shipment_id) REFERENCES dcsa_ebl_v1_0.shipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_party ADD CONSTRAINT "FK_Notify Party_Party"
	FOREIGN KEY (party_id) REFERENCES dcsa_ebl_v1_0.party (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_party ADD CONSTRAINT "FK_Notify Party_Shipment"
	FOREIGN KEY (shipment_id) REFERENCES dcsa_ebl_v1_0.shipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_transport ADD CONSTRAINT "FK_ShipmentTransportLeg_Shipment"
	FOREIGN KEY (shipment_id) REFERENCES dcsa_ebl_v1_0.shipment (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.shipment_transport ADD CONSTRAINT "FK_ShipmentTransportLeg_Transport Leg"
	FOREIGN KEY (transport_id) REFERENCES dcsa_ebl_v1_0.transport (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport ADD CONSTRAINT "FK_Transport Leg_Transport Call"
	FOREIGN KEY (departure_transport_call_id) REFERENCES dcsa_ebl_v1_0.transport_call (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport ADD CONSTRAINT "FK_Transport Leg_Transport Call_02"
	FOREIGN KEY (arrival_transport_call_id) REFERENCES dcsa_ebl_v1_0.transport_call (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport ADD CONSTRAINT "FK_Transport_Mode Of Transport"
	FOREIGN KEY (mode_of_transport_code) REFERENCES dcsa_ebl_v1_0.mode_of_transport (mode_of_transport_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_call ADD CONSTRAINT "FK_Transport Call_Location"
	FOREIGN KEY (location_id) REFERENCES dcsa_ebl_v1_0.location (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_call_voyage ADD CONSTRAINT "FK_Transport Call Voyage_Transport Call"
	FOREIGN KEY (transport_call_id) REFERENCES dcsa_ebl_v1_0.transport_call (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_call_voyage ADD CONSTRAINT "FK_Transport Call Voyage_Voyage"
	FOREIGN KEY (voyage_id) REFERENCES dcsa_ebl_v1_0.voyage (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_document ADD CONSTRAINT "FK_Transport Document_Location"
	FOREIGN KEY (place_of_issue) REFERENCES dcsa_ebl_v1_0.location (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_document ADD CONSTRAINT "FK_Transport Document_Party"
	FOREIGN KEY (issuer) REFERENCES dcsa_ebl_v1_0.party (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_document ADD CONSTRAINT "FK_Transport Document_Shipping Instruction"
	FOREIGN KEY (shipping_instruction_number) REFERENCES dcsa_ebl_v1_0.shipping_instruction (shipping_instruction_number) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_document ADD CONSTRAINT "FK_Transport Document_Transport Document Type"
	FOREIGN KEY (transport_document_code) REFERENCES dcsa_ebl_v1_0.transport_document_type (transport_document_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_document_carrier_clauses ADD CONSTRAINT "FK_Transport Document Carrier Clauses_Carrier Clauses"
	FOREIGN KEY (carrier_clauses_id) REFERENCES dcsa_ebl_v1_0.carrier_clauses (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.transport_document_carrier_clauses ADD CONSTRAINT "FK_Transport Document Carrier Clauses_Transport Document"
	FOREIGN KEY (transport_document_id) REFERENCES dcsa_ebl_v1_0.transport_document (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dcsa_ebl_v1_0.vessel ADD CONSTRAINT "FK_Vessel_Transport"
	FOREIGN KEY (transport_id) REFERENCES dcsa_ebl_v1_0.transport (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN dcsa_ebl_v1_0.booking.booking_datetime
	IS 'The date and time of the booking request.';

COMMENT ON COLUMN dcsa_ebl_v1_0.cargo_item.commodity_type
	IS 'HS6: e.g. 2468 which could be metal';

COMMENT ON TABLE dcsa_ebl_v1_0.cargo_item_equipment
	IS 'A shipment may be fulfilled using part or all of an equipment or may be transported using multiple pieces of equipment. This entity captures how the shipment will be fulfilled/split using one or more pieces of equipment. add: weight, volume and stuffing and package';

COMMENT ON COLUMN dcsa_ebl_v1_0.ebl_endorsement_chain.signature
	IS 'Digital signature of the previous title holder';

COMMENT ON TABLE dcsa_ebl_v1_0.equipment
	IS 'Used for storing cargo in/on during transport. The equipment  "size/type" is defined by the ISO 6346 code. The most common equipment size/type is 20''/40''/45'' Dry Freight Container, but a number of different versions exists.  ';

COMMENT ON COLUMN dcsa_ebl_v1_0.equipment.equipment_reference
	IS 'The unique identifier for the equipment, which should follow the BIC ISO Container Identification Number where possible. According to ISO 6346, a container identification code consists of a 4-letter prefix and a 7-digit number (composed of a 3-letter owner code, a category identifier, a serial number and a check-digit). If a container does not comply with ISO 6346, it is suggested to follow Recommendation #2 “Container with non-ISO identification” from SMDG.';

COMMENT ON COLUMN dcsa_ebl_v1_0.equipment.iso_equipment_code
	IS 'Unique code for the different equipment size/type used for transporting commodities. The code is a concatenation of ISO Equipment Size Code and ISO Equipment Type Code A and follows the ISO 6346 standard.';

COMMENT ON TABLE dcsa_ebl_v1_0.mode_of_transport
	IS 'The code specifying the transport mode for the logistic transport movement, following the UN/CEFACT Recommendation 19 - Codes for Modes of Transport mapped to the transport types as defined in the DCSA Glossary of Terms.';

COMMENT ON COLUMN dcsa_ebl_v1_0.mode_of_transport.mode_of_transport_code
	IS 'The code specifying the mode (e.g. transport by rail) for the transport. The code follows UN/CEFACT Recommendation 19 - Codes for Modes of Transport.';

COMMENT ON COLUMN dcsa_ebl_v1_0.mode_of_transport.mode_of_transport_name
	IS 'The name of the mode of transport. The code follows UN/CEFACT Recommendation 19 - Codes for Modes of Transport';

COMMENT ON COLUMN dcsa_ebl_v1_0.mode_of_transport.mode_of_transport_description
	IS 'The description of the mode of transport as detailed by UN/CEFACT Recommendation 19 - Codes for Modes of Transport';

COMMENT ON COLUMN dcsa_ebl_v1_0.mode_of_transport.dcsa_transport_type
	IS 'The DCSA defined types of transport as used in events linked to the Mode of Transport.';

COMMENT ON COLUMN dcsa_ebl_v1_0.package_code.un_package_code
	IS 'e.g. UN00001899';

COMMENT ON COLUMN dcsa_ebl_v1_0.references.reference_type
	IS 'e.g. CR, PO, SI, FF';

COMMENT ON TABLE dcsa_ebl_v1_0.seal_source
	IS 'The source of the seal (carrier, shipper, TBD)';

COMMENT ON TABLE dcsa_ebl_v1_0.seal_type
	IS 'The type of seal used for sealing the container (bolt, wire, keyless padlock).';

COMMENT ON TABLE dcsa_ebl_v1_0.shipment
	IS 'A Shipment is the realization of a customer booking for which all containers have a common routing and details of scheduling. PoR, PoR, PoD, place of delivery (links to UN Location), reference';

COMMENT ON COLUMN dcsa_ebl_v1_0.shipment.transport_document_id
	IS 'Bill of lading number is an identifier that links to a shipment. Bill of lading is the legal document issued to the customer which confirms the carrier''s receipt of the cargo from the customer acknowledging goods being shipped and specifying the terms of delivery.';

COMMENT ON COLUMN dcsa_ebl_v1_0.shipment.collection_datetime
	IS 'The date and the time that the shipment items need to be collected from the origin.';

COMMENT ON COLUMN dcsa_ebl_v1_0.shipment.delivery_datetime
	IS 'The date (and when possible time) that the shipment items need to be delivered to the destination.';

COMMENT ON COLUMN dcsa_ebl_v1_0.shipment.carrier_code
	IS 'The Carrier Code represents a concatenation of the Code List Provider Code and the Code List Provider. A hyphen is used between the two codes. The unique carrier identifier is sourced from either the NMFTA SCAC codes list or the SMDG Master Liner codes list.';

COMMENT ON TABLE dcsa_ebl_v1_0.shipment_equipment
	IS 'A table containing the information for an equipment for the duration of the shipment it contains.';

COMMENT ON TABLE dcsa_ebl_v1_0.shipment_location
	IS 'Entity expressing which locations are involved in a Shipment:
Mandatory location types:
* Place of Receipt
* Place of Delivery
* Pre-carriage by
* Onward In-land Routing
* Port of Loading
* Port of Discharge
Origin of goods';

COMMENT ON TABLE dcsa_ebl_v1_0.shipment_location_type
	IS '* Place of Receipt
* Place of Delivery
* Pre-carriage by
* Onward In-land Routing
* Port of Loading
* Port of Discharge
Origin of goods';

COMMENT ON TABLE dcsa_ebl_v1_0.transport
	IS 'The transport instance used to convey goods or other objects from place to place during logistics cargo movements.';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport.transport_reference
	IS 'The reference for the transport, e.g. when the mode of transport is a vessel, the Transport Reference will be the vessel IMO number.';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport.transport_name
	IS 'The name of the particular transport instance, e.g. for a vessel this is the vessel name';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport.mode_of_transport
	IS 'The code specifying the means of transport, e.g. the named vessel executing the transporting.';

COMMENT ON TABLE dcsa_ebl_v1_0.transport_call
	IS 'A list of all of the locations involved in a journey. Notes: a journey consists of all of these locations...';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport_call.transport_call_sequence_number
	IS 'Transport operator''s key that uniquely identifies each individual call. Essential to distinguish between 2 separate calls at the same location.  ';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport_document.issuer
	IS 'name of the carrier who issues the BL';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport_document.document_status
	IS 'SI Received, Drafted, Pending Approval, Approved, Issued, Surrendered';

COMMENT ON TABLE dcsa_ebl_v1_0.transport_document_type
	IS 'An entity containing the reference dta for the different transport document types.';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport_document_type.transport_document_code
	IS 'The type of the transport document (i.e. BOL (bill of lading) or SWB (Sea Waybill). @adding eBL';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport_document_type.transport_document_type_name
	IS 'The full names of the document types (Bill of Lading or Sea Waybill).';

COMMENT ON COLUMN dcsa_ebl_v1_0.transport_document_type.transport_document_type_description
	IS 'A description of the different docuemtn types.';

COMMENT ON TABLE dcsa_ebl_v1_0.un_location
	IS 'A location as defined by UNECE and commonly known as "UN/LOCODE" ("United Nations Code for Trade and Transport Locations"). The UN Location identifies a location in the sense of a city/a town/a village, being the smaller administrative area existing as defined by the competent national authority in each country.';

COMMENT ON COLUMN dcsa_ebl_v1_0.un_location.un_location_code
	IS 'The UN Location Code identifies a location in the sense of a city/a town/a village, being the smaller administrative area existing as defined by the competent national authority in each country. A complete UN Location Code is a combination of a 2-character country code and a 3-character city/town/area LOCODE, e.g. BEANR is known as the city of Antwerp (ANR), which is located in Belgium (BE).';

COMMENT ON COLUMN dcsa_ebl_v1_0.un_location.un_location_name
	IS 'The name of the location as defined by the UN/ECE';

COMMENT ON COLUMN dcsa_ebl_v1_0.un_location.location_code
	IS 'Location Code identifies a location in the sense of a city/a town/a village, being the smaller administrative area existing as defined by the competent national authority in each country. Location Code is a 3-character code e.g. ANR for Antwerp.';

COMMENT ON COLUMN dcsa_ebl_v1_0.un_location.country_code
	IS 'The two-letter ISO 3166 country code. E.g. BE for Belgium.';

COMMENT ON TABLE dcsa_ebl_v1_0.vessel
	IS 'A floating structure with either internal mode of propulsion designed for the transport of cargo and/or passengers. Vessels are sea going but can be either mother vessels (Deep sea/Ocean) and feeder vessels (Short Sea). Defined by the DCSA.';

COMMENT ON COLUMN dcsa_ebl_v1_0.vessel.vessel_imo_number
	IS 'The unique reference for a registered Vessel. The reference is the International Maritime Organization (IMO) number, also sometimes known as the Lloyd''s register code.';

COMMENT ON COLUMN dcsa_ebl_v1_0.vessel.vessel_name
	IS 'The name of the Vessel given by the Vessel Operator e.g. Emma Maersk';

COMMENT ON COLUMN dcsa_ebl_v1_0.vessel.vessel_flag
	IS 'The flag of the vessel e.g. DK';

COMMENT ON COLUMN dcsa_ebl_v1_0.vessel.vessel_call_sign_number
	IS 'A unique alphanumeric identity that belongs to the vessel. Each Call Sign begins with the Call Sign alphanumeric prefix that indicates nationality, e.g. prefixes allocated to the United Kingdom are 2, G, M, VP-VQ, VS, ZB-ZJ, ZN-ZO and ZQ. The prefix is usually followed by 2 or 3 alphanumeric characters. For example, Cunard Lines Queen Mary 2 has the Call Sign W6RO.';

COMMENT ON COLUMN dcsa_ebl_v1_0.vessel.vessel_operator_carrier_code
	IS 'The carrier who is in charge of the vessel operations';

COMMENT ON COLUMN dcsa_ebl_v1_0.vessel.transport_id
	IS 'The identifier of the Transport.';

COMMENT ON TABLE dcsa_ebl_v1_0.voyage
	IS 'A part of a service roundtrip that normally changes at the geographical “end-point” of a vessel rotation and as such that specific port call can have two voyages – One for the discharge of final shipments on the “current” voyage, and a new voyage number identifying the commencement of loading shipments (for allocation purposes). One rotation will normally have 2 voyages, one on each haul.';

COMMENT ON COLUMN dcsa_ebl_v1_0.voyage.id
	IS 'The identifier of the Voyage.';

COMMENT ON COLUMN dcsa_ebl_v1_0.voyage.carrier_voyage_number
	IS 'The identifier of the Voayge. The identifier is vessel operator specific.';

COMMENT ON COLUMN dcsa_ebl_v1_0.voyage.service_id
	IS 'The identifier of the Service.';
