version: '3.5'
services:
    dcsa-test-db:
        container_name: dcsa_db
        environment:
            POSTGRES_PASSWORD: "change_this_password"
        build:
            datamodel/
        ports:
            - 5432:5432

